### ISSUE TITLE
Does not seem to be able to run locally

### ISSUE THREAD

**Issue by zeekhoo** [andymarch/OAuth-For-Okta-APIs#3]
The redirect_uri from .env seems to be always appended with /authorization-code/default so my authorize request is failing with an un-whitelisted redirect_uri error message.

**Comment by andymarch** [comment]
Hey Zee, that's a behaviour of passport (/default is always the tenant configured in the env file rather than pulled from UDP).

My localhost env file has the following for redirect_uri:
`REDIRECT_URI=http://localhost:3000`
With an application whitelist of containing:
`
http://localhost:3000/authorization-code/default
`
